# Generated by Django 4.0.3 on 2022-03-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenseApp', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Address',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='City',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='FullName',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Mobile',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='State',
            field=models.CharField(default='', max_length=30),
        ),
    ]
