# Generated by Django 4.0.3 on 2022-04-05 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenseApp', '0004_budget_expensecategory_saving_alter_profile_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='Profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenseApp.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='Profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenseApp.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saving',
            name='Profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenseApp.profile'),
            preserve_default=False,
        ),
    ]
